name = "modlynx-canonical-worker"
main = "src/index.js"
compatibility_date = "2025-08-01"

account_id  = "400c185e50b94db0e2b3f7a2914d8273"
workers_dev = false

[triggers]
  routes = ["modlynx.xyz/*"]
